version: '3.0'
services:
  vcpingmain:
    build:
      context: ./
      dockerfile: dockerfile
    image: fusate/vcpingmain
    restart: always
    tty: true # make sure python print doesn't buffer with this
    volumes:
      - vcping-data:/data/

volumes:
  vcping-data:
